title = "Go London User Group"
# For local deployment swap comments on the following two properties
baseURL = "https://go-london-user.group"
# baseURL = "http://localhost:1313"
languageCode = "en-gb"
theme = "gohugo-theme-ananke"
# themesDir = "../themes/"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoLondonUserGrp"
  instagram = ""
  youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
